### ISSUE TITLE
Ambiguity for `registry` in documentation

### ISSUE THREAD

**Issue by catfishlty** [robkaandorp/drone-portainer#10]
## In Doc
```
registry: <name of private registry>
```

It said that it should be replaced as name.

![1675839011](https://user-images.githubusercontent.com/12734411/217455630-b3653c2d-a724-46b0-8247-9eb3dbea469b.png)

## In Code
https://github.com/robkaandorp/drone-portainer/blob/75be548383a2e3b97c941f34ca0a4b1a400a5bd1/src/index.ts#L7
https://github.com/robkaandorp/drone-portainer/blob/75be548383a2e3b97c941f34ca0a4b1a400a5bd1/src/index.ts#L77

But in code, it's URL of private registry. So I think it should be fixed in one side, `name` or `url`

**Comment by robkaandorp** [comment]
You are right. I will clarify this in the README. Thanks!
