### ISSUE TITLE
Support Portainer 2.9.1

### ISSUE THREAD

**Issue by Zwordi** [robkaandorp/drone-portainer#7]
Hello,

I’ve updated my Portainer from 2.1 to 2.9.1.
Seems that some paths have changed and even if the CI/CD went well, my stack doesn’t get updated.

Error on CI/CD : none
Logs:
```
latest: Pulling from robkaandorp/drone-portainer
--
2 | Digest: sha256:3488fb5c34580805db90d11c6825c2dbf89f98cb1b40f21007b4f07043aabde2
3 | Status: Image is up to date for robkaandorp/drone-portainer:latest
4 | (node:1) UnhandledPromiseRejectionWarning: TypeError: registriesResponse.data.find is not a function
5 | at /app/dist/index.js:72:58
6 | at Generator.next (<anonymous>)
7 | at fulfilled (/app/dist/index.js:5:58)
8 | at process._tickCallback (internal/process/next_tick.js:68:7)
9 | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
10 | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

On the portainer logs i’ve got :

```
portainer       | level=info msg="2021/10/17 08:12:11 http error: Permission denied to list registries, use /endpoints/:endpointId/registries route instead (err=Access denied to resource) (code=403)"
```

So the log suggest to update the path made for checking the registries settings for the environment but as I don’t have the full picture on this project it’s better to check with you first. 

Let me know if I can help,

Regards,

**Comment by robkaandorp** [comment]
This error seems related to getting the list of configured registries from the Portainer API. Are you sure your Portainer credentials are set correctly?

Regards, Rob

**Comment by robkaandorp** [comment]
Or maybe the registriesResponse.data field is not an array. I am not sure why that could happen, I will have to reproduce and debug the issue, but I can't right now. A console.log(registriesResponse.data) output right after `await axios.get("/registries");` would be very helpful. Can you somehow try that?

Regards, Rob

**Comment by Zwordi** [comment]
Rob,

Glad to help. I will fork and give a try in order to grab the output.

Regards,
Zwordi
